
LYFT_CLIENT_ID = 'K6LJpE0ybWOX'
LYFT_CLIENT_SECRET = 'WHVD_bcjKn35A-jGOqKnPZwwTGbaOymN'
UBER_SERVER_TOKEN = 'aBtiXJ-CtGuMysPbFnNueeiFInE7IuzUucsPT4vO'

GOOGLE_MAPS_API_KEY = 'AIzaSyACSsnuIq_37IO7dZnLTjpHQAXdQL_mlRM'